{
  stdenv,
  emscripten,
  cmake,
  fetchFromGitHub
}:
stdenv.mkDerivation {
  name = "sdl";

  src = fetchFromGitHub {
    tag = "release-2.32.0";
    repo = "SDL";
    owner = "libsdl-org";
    hash = "sha256-BdyMlttrDwQMoz+bO6bfU3bh0xKnT8yQF6nb6OGRbHw=";
  };

  buildInputs = [
    emscripten
    cmake
  ];

  configurePhase = ''
    export EM_CACHE=/tmp/emcache
    mkdir -p $EM_CACHE
    cp -r ${emscripten}/share/emscripten/cache/* $EM_CACHE/ || true
    chmod -R +w $EM_CACHE

    mkdir -p $PWD/build
    cd $PWD/build
    emcmake cmake $src \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_FLAGS="-pthread" \
      -DCMAKE_CXX_FLAGS="-pthread" \
      -DSDL_SHARED=OFF \
      -DSDL_STATIC=ON \
      -DSDL_TEST=OFF \
      -DSDL_TESTS=OFF \
      -DSDL2_DISABLE_SDL2MAIN=ON \
      -G "Unix Makefiles"
  '';

  buildPhase = ''
    export EM_CACHE=/tmp/emcache
    cd $NIX_BUILD_TOP/source/build
    emmake make -j$(nproc) SDL2-static
  '';

  installPhase = ''
    mkdir -p $out/include/SDL2
    mkdir -p $out/lib
    
    BUILD_DIR=$NIX_BUILD_TOP/source/build
    
    # First, copy the generated SDL_config.h (the important one generated by cmake)
    # It's at include-config-release/SDL2/SDL_config.h
    cp $BUILD_DIR/include-config-release/SDL2/SDL_config.h $out/include/SDL2/
    
    # Copy all headers from SDL source EXCEPT SDL_config.h (we already have the generated one)
    for f in $src/include/*.h; do
      fname=$(basename "$f")
      if [ "$fname" != "SDL_config.h" ]; then
        cp "$f" $out/include/SDL2/
      fi
    done
    
    # Copy the built library
    cp $BUILD_DIR/libSDL2.a $out/lib/
  '';

}
